/// A read-only filesystem interface.
interface read-filesystem {
    use types.{bytes-stream};
    
    /// Handle to an open file.
    resource file {
        /// Name of the file, including extension.
        name: func() -> string;

        /// Read the entire contents of the file.
        /// 
        /// If the file is larger than what can fit in memory see `read-stream`.
        read: func() -> list<u8>;

        /// Return a resource that asynchronously reads bytes from this file.
        read-stream: func() -> bytes-stream;
    }
}

/// A writeable filesystem interface.
interface write-filesystem {
    use types.{failable-future};

    resource write-directory {
        /// Create a new file with the specified name.
        create-file: func(name: string) -> write-file;

        /// Create a new directory with the specified name.
        create-directory: func(name: string) -> write-directory;
    }

    resource write-file {
        /// Asynchronously writes bytes to this file.
        append: func(data: list<u8>) -> failable-future;

        /// Asynchronously write bytes to an extended attribute on this file.
        write-xattr: func(name: string, data: list<u8>) -> failable-future;

        /// Set the mtime of this file.
        set-mtime: func(millis: u64) -> failable-future;

        /// Close this file, flushing content to disk.
        close: func() -> failable-future;
    }
}
