/// A read-only filesystem interface.
interface read-filesystem {
    /// Handle to an open file.
    resource file {
        /// Name of the file, including extension.
        name: func() -> string;

        /// Read the content of the file.
        read: func() -> list<u8>;
    }
}
