/// A read-only filesystem interface.
interface read-filesystem {
    use types.{bytes-stream};
    
    /// Handle to an open file.
    resource file {
        /// Name of the file, including extension.
        name: func() -> string;

        /// Read the entire contents of the file.
        /// 
        /// If the file is larger than what can fit in memory see `read-stream`.
        read: func() -> list<u8>;

        /// Return a resource that asynchronously reads bytes from this file.
        read-stream: func() -> bytes-stream;
    }
}

/// A writeable filesystem interface.
interface write-filesystem {
    use types.{bytes-sink};

    resource write-file {
        /// Create a new file with the specified name.
        create: func(name: string) -> write-file;

        /// Return a resource that asynchronously writes bytes to this file.
        write-sink: func() -> bytes-sink;
    }
}
