/// An interface for making HTTP requests.
interface http {
    use types.{bytes-stream, waker};
    
    resource client {
        /// Make an HTTP `GET` request.
        get: func(request: request) -> response-poll;
    }

    /// An HTTP request.
    record request {
        url: string,
        headers: list<tuple<string, string>>,
    }

    /// An HTTP response.
    resource response {
        status: func() -> u16;
        headers: func() -> list<tuple<string, string>>;
        body: func() -> bytes-stream;
    }

    /// Polling status states for a `response`.
    variant response-poll {
        pending,
        ready(response),
    }
}
