/// An interface for logging within a rule set.
interface logging {
    /// Level of an individual event.
    enum level {
        trace,
        debug,
        info,
        warn,
        error,
    }

    /// Additional named fields that will emitted an event.
    record field {
        name: string,
        value: string,
    }

    /// Line or location in source code where an event was emitted.
    record location {
        file-path: option<string>,
        line: option<u32>,
    }

    /// Function to log an event.
    event: func(level: level, message: string, location: location, fields: list<field>);
}
