/// A that can resolve targets given some configuration file.
interface resolver {
    use read-filesystem.{file};
    use types.{target};

    /// Returns a glob pattern that expresses what additional files this
    /// resolver is interested in.
    /// 
    /// By default every resolver is passed `pb.toml` files.
    additional-interest-glob: func() -> option<string>;
    
    /// Returns all targets present defined in the provided file.
    resolve-target: func(file: file) -> result<list<target>, string>;
}
