/// Types related to target resolution.
interface types {
    /// An individual build target.
    record target {
        /// Name of the build target.
        name: string,
        /// Location of this target (e.g. build file).
        location: string,
        /// Attributes/configuration of this target.
        attributes: list<tuple<string, attribute>>,
    }

    variant attribute {
        /// Boolean value - `true` or `false`.
        boolean(bool),
        /// Text value - Raw value _not_ another target.
        text(string),
        /// List of Text.
        text-list(list<string>),
        /// Target in the current workspace.
        target(string),
        /// List of Targets
        target-list(list<string>),
    }
}
